# Regenerate golden_frame.bin — the cross-language conformance fixture.
#
# The Python add-in WRITES the frame format and the C# client READS it. Two
# implementations of one format is exactly the situation where they drift and
# nobody notices until the geometry looks subtly wrong on hardware. So a frame
# built by the real Python code path is checked in, and FusionChecks.cs asserts
# against it: change either side's idea of the format and the C# suite fails.
#
# Run:  python fusion/tests/make_golden.py
#
# Only re-run this when the format is INTENTIONALLY changed. Regenerating it to
# make a failing test pass would defeat the entire point of having it.

import io
import os
import sys

sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "FusionBridge")
)

from bridge import protocol  # noqa: E402

# A 1 cm cube, exactly as Fusion reports geometry: indexed, in centimetres.
COORDS_CM = [
    0, 0, 0,  1, 0, 0,  1, 1, 0,  0, 1, 0,
    0, 0, 1,  1, 0, 1,  1, 1, 1,  0, 1, 1,
]
INDICES = [
    0, 3, 2,  0, 2, 1,
    4, 5, 6,  4, 6, 7,
    0, 1, 5,  0, 5, 4,
    2, 3, 7,  2, 7, 6,
    1, 2, 6,  1, 6, 5,
    3, 0, 4,  3, 4, 7,
]


def main():
    soup = protocol.expand_triangles([float(c) for c in COORDS_CM], INDICES)

    frame = protocol.build_frame(
        [
            {"path": "Root:1/Cube:1",   "name": "Cube",   "visible": True,  "tris": soup},
            {"path": "Root:1/Hidden:1", "name": "Hidden", "visible": False, "tris": soup},
        ],
        document="GoldenCube",
        revision="gold01",
        dropped=7,
        note="generated by fusion/tests/make_golden.py",
    )

    out = os.path.join(os.path.dirname(os.path.realpath(__file__)), "golden_frame.bin")
    io.open(out, "wb").write(frame)
    print("wrote %s — %d bytes, %d triangles" % (out, len(frame), len(soup) // 9 * 2))


if __name__ == "__main__":
    main()
